name: Build and Package Overnote

on:
  push:
  #    tags:
  #      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest] # For testing purposes, only run on Ubuntu for now

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build JAR with dependencies
        run: mvn clean package

      - name: Create native installer
        run: |
          mkdir -p dist

          # Determine installer type
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            TYPE=deb
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            TYPE=msi
          else
            TYPE=pkg
          fi

          jpackage \
            --input target \
            --name Overnote \
            --main-jar Overnote-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class eus.overnote.Main \
            --type "$TYPE" \
            --dest dist \
            --app-version "${{ github.ref_name || '0.0.0-test' }}" \

      - name: Upload packaged app
        uses: actions/upload-artifact@v4
        with:
          name: overnote-${{ matrix.os }}
          path: dist/
